ALTER TABLE packages ADD COLUMN IF NOT EXISTS file_path TEXT NOT NULL DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS layer_id TEXT NOT NULL DEFAULT '';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS target TEXT NOT NULL DEFAULT '';

ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS pkg_path TEXT NOT NULL DEFAULT '';
ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS layer_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS container TEXT NOT NULL DEFAULT '';
